apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: wire-connector
    app.kubernetes.io/part-of: wire-connector
    app.kubernetes.io/version: tbd
  name: wire-connector-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - links
  - links/status
  - nodes
  - nodes/status
  - endpoints
  - endpoints/status
  - targets
  - targets/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - nodeconfigs
  - nodeconfigs/status
  - nodemodels
  - nodemodels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch