apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wire-connectore-controller
  namespace: network-system
spec:
  selector:
    matchLabels:
      fn.kptgen.dev/controller: wire-connector-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tbd
        app.kubernetes.io/instance: tbd
        app.kubernetes.io/managed-by: kpt
        app.kubernetes.io/name: wire-connector
        app.kubernetes.io/part-of: wire-connector
        app.kubernetes.io/version: tbd
        fn.kptgen.dev/controller: wire-controller-controller
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: wire-connector-controller
      containers:
      - name: wire-connector
        image: image: europe-docker.pkg.dev/srlinux/eu.gcr.io/wire-connector:latest
        command:
        - /manager
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]
