apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: wire-connector
    app.kubernetes.io/part-of: wire-connector
    app.kubernetes.io/version: tbd
  name: wire-connector-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - links
  - links/status
  - nodes
  - nodes/status
  - nodepools
  - nodepools/status
  - endpoints
  - endpoints/status
  - targets
  - targets/status
  - topologies
  - topologies/status
  - logicalendpoints
  - logicalendpoints/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - nodeconfigs
  - nodeconfigs/status
  - nodemodels
  - nodemodels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topo.nephio.org
  resources:
  - interconnects
  - interconnects/status
  - logicalinterconnects
  - logicalinterconnects/status
  - rawtopologies
  - rawtopologies/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - configmaps
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vxlan.resource.nephio.org
  resources:
  - vxlanindexes
  - vxlanindexes/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete